// global
export const CHANGE_SEASON = "CHANGE_SEASON";
export const CHANGE_SEASON_DEFAULT = "CHANGE_SEASON_DEFAULT";

// farms
export const GET_FARMS = "GET_FARMS";
export const SEARCH_FARMS = "SEARCH_FARMS";
export const CHANGE_FARM_FILTER = "CHANGE_FARM_FILTER";
export const INCREASE_FARMS_AMOUNT = "INCREASE_FARMS_AMOUNT";
export const RESET_FARMS_AMOUNT = "RESET_FARMS_AMOUNT";

// farm
export const GET_FARM = "GET_FARM";
export const OPEN_FARM_LIGHTBOX = "OPEN_FARM_LIGHTBOX";
export const CLOSE_FARM_LIGHTBOX = "CLOSE_FARM_LIGHTBOX";
export const FARM_LIGHTBOX_NEXT = "FARM_LIGHTBOX_NEXT";
export const FARM_LIGHTBOX_PREV = "FARM_LIGHTBOX_PREV";
export const SET_SOURCES_FARM_LIGHTBOX = "SET_SOURCES_FARM_LIGHTBOX";
export const CLEAR_FARM = "CLEAR_FARM";

// drawer
export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";
export const DOCK_DRAWER = "DOCK_DRAWER";
export const UNDOCK_DRAWER = "UNDOCK_DRAWER";
export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
export const UPDATE_AUTODOCK_DRAWER = "UPDATE_AUTODOCK_DRAWER";

// discord
export const UPDATE_DISCORD = "UPDATE_DISCORD";
