export const CHANGE_FARM_FILTER = "CHANGE_FARM_FILTER";
export const OPEN_FARM_LIGHTBOX = "OPEN_FARM_LIGHTBOX";
export const CLOSE_FARM_LIGHTBOX = "CLOSE_FARM_LIGHTBOX";
export const FARM_LIGHTBOX_NEXT = "FARM_LIGHTBOX_NEXT";
export const FARM_LIGHTBOX_PREV = "FARM_LIGHTBOX_PREV";
export const SET_SOURCES_FARM_LIGHTBOX = "SET_SOURCES_FARM_LIGHTBOX";
